/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint for system monitoring. Used by load balancers and monitoring systems to verify system availability. Requires no authentication.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description System is operational */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/member/api/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign up
         * @description Registers a member with email and password. The password is PBKDF2-hashed into `member_password`, kept in a separate table from the `member` profile, and the raw value is never stored.
         *     A session is issued as part of the same request, so the response already carries the `session` cookie and the caller is logged in — no follow-up login round trip.
         *     `email` is trimmed and lower-cased before the uniqueness check.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: email
                         * @description Login ID. Already registered → 409.
                         * @example taro@example.com
                         */
                        email: string;
                        /**
                         * @description Raw password. Shorter than 8 characters → 400.
                         * @example password123
                         */
                        password: string;
                        /**
                         * @description Display name. Empty → 400.
                         * @example 山田 太郎
                         */
                        name: string;
                        /**
                         * @description Reading of the display name, full-width katakana only (the confirmed roster sorts by it). Anything else → 400.
                         * @example ヤマダタロウ
                         */
                        nameKana: string;
                    };
                };
            };
            responses: {
                /** @description Registered, session cookie set */
                201: {
                    headers: {
                        /** @description Signed session cookie */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: int64
                             * @description Management ID of the created member
                             * @example 1
                             */
                            id: number;
                        };
                    };
                };
                400: components["responses"]["400"];
                409: components["responses"]["409"];
                500: components["responses"]["500"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/member/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in
         * @description Looks the member up by email and compares the supplied password against the stored PBKDF2 hash. On success a fresh session row is inserted and the `session` cookie is set.
         *     An unknown email and a wrong password both return the same 401 with the same message, so the response cannot be used to probe which addresses are registered.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: email
                         * @example taro@example.com
                         */
                        email: string;
                        /** @example password123 */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Authenticated, session cookie set */
                200: {
                    headers: {
                        /** @description Signed session cookie */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: int64
                             * @description Management ID of the authenticated member
                             * @example 1
                             */
                            id: number;
                        };
                    };
                };
                400: components["responses"]["400"];
                401: components["responses"]["401"];
                500: components["responses"]["500"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/member/api/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log out
         * @description Deletes the `member_session` row the cookie points at, then discards the cookie. Server side goes first, so the token is dead even for a client that keeps its copy.
         *     Idempotent: a request with no cookie, or one whose signature no longer verifies, still returns 204 rather than an error — there is nothing to reveal and nothing left to do.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logged out, session cookie discarded */
                204: {
                    headers: {
                        /** @description Discard instruction for the session cookie (Max-Age=0) */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                500: components["responses"]["500"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/member/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get my profile
         * @description Resolves the logged-in member from the `session` cookie and returns the public profile. Authentication status is conveyed by the HTTP code (200 / 401), not a payload field.
         *     The cookie's HMAC signature is verified before any query runs, so a tampered cookie is rejected without touching the database. A token whose `member_session` row is gone — logged out, or never issued — is a 401 even when the signature still checks out, because the row is the source of truth.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current authenticated member */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: int64
                             * @description Management ID (internal sequence)
                             * @example 1
                             */
                            id: number;
                            /**
                             * Format: uuid
                             * @description Public identifier. Prefer this over `id` when exposing a member.
                             * @example 6486431a-3cac-4ba2-b32d-e67b673b8f76
                             */
                            uuid: string;
                            /**
                             * @description Display name
                             * @example 山田 太郎
                             */
                            name: string;
                            /**
                             * Format: email
                             * @description Login ID
                             * @example taro@example.com
                             */
                            email: string;
                        };
                    };
                };
                401: components["responses"]["401"];
                500: components["responses"]["500"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event/api/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Propose an event
         * @description Publishes an event and, in the same request, records the proposer as its first entry — the count that decides confirmation includes them.
         *     Who is proposing comes from the `session` cookie and is never part of the body. The proposer stays anonymous: nothing in any response reveals them, and after confirmation they appear only as one name among the participants.
         *     The response carries the `code` alone. That is the event's whole address — what the bot posts to Slack, and all a visitor needs — while the numeric id stays server-side.
         *     Times are JST and carry no offset.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description What the event is. A single line — where to meet is written in here too, since an event holds no place of its own.
                         * @example 今日ランチ行きたい
                         */
                        title: string;
                        /**
                         * @description When to meet, JST without an offset. Must be in the future and within a year.
                         * @example 2026-09-03T12:00
                         */
                        startAt: string;
                        /**
                         * @description When to stop judging confirmation. Omit it and the meeting time is used. Must satisfy now < closeAt <= startAt.
                         * @example 2026-09-03T11:00
                         */
                        closeAt?: string | null;
                        /**
                         * @description How many it takes, the proposer included.
                         * @example 4
                         */
                        minEntries: number;
                        /**
                         * @description Where the bot announces it.
                         * @example C0LUNCH
                         */
                        slackChannelId: string;
                    };
                };
            };
            responses: {
                /** @description Published */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Public identifier, used as the event's URL.
                             * @example xxd6Y46QH4OpL_CeMWP7_A
                             */
                            code: string;
                        };
                    };
                };
                400: components["responses"]["400"];
                401: components["responses"]["401"];
                500: components["responses"]["500"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/place/api/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Review a place
         * @description Writes a star and, if there is anything to add, a line about the place.
         *     A review is written afresh every visit, so posting twice about the same place is two reviews rather than an overwrite — `createdAt` is what says when each visit happened.
         *     Reviews carry the writer's name. This is the one place in the application where a member is deliberately not anonymous: a colleague's "I like this one" is the reason the reviews exist at all.
         *     Who is writing comes from the `session` cookie and is never part of the body.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description The place being reviewed, named by the identifier in its URL. Unknown → 404.
                         * @example 6a0b6598-d3be-48ef-8871-2850d29dc300
                         */
                        placeUuid: string;
                        /**
                         * @description Outside 1..5 → 400.
                         * @example 4
                         */
                        star: number;
                        /**
                         * @description A single line, at most 200 characters. Omit it and the star stands on its own.
                         * @example 11:45 なら並ばず入れた。味玉推し
                         */
                        comment?: string | null;
                    };
                };
            };
            responses: {
                /** @description Written */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: int64
                             * @description Management ID of the review, used to edit or delete it.
                             * @example 1
                             */
                            id: number;
                        };
                    };
                };
                400: components["responses"]["400"];
                401: components["responses"]["401"];
                404: components["responses"]["404"];
                500: components["responses"]["500"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: {
        /** @description リクエスト不正。JSON のパース失敗（`Parsing Failure: ...`）、 デコード失敗（`Decoding Failure: ...`）、 バリデーション違反のいずれか。 */
        400: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
        /** @description 認証失敗。Cookie 未送信 (`The session token not found`)、 署名不正 (`Invalid token signature`)、 セッション失効 (`The session is no longer valid`)、 資格情報の不一致 (`invalid email or password`) のいずれか。 */
        401: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
        /** @description 指定されたものが見つからない。存在しない識別子と、削除済みの識別子は 同じ答えを返す（区別すると存在の有無が漏れる）。 */
        404: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
        /** @description 競合。登録しようとした email が既に使われている。 */
        409: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
        /** @description 想定外のサーバーエラー。mvc.ErrorHandler が整形して返す。 */
        500: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example true */
                    error: boolean;
                    /** @example Unexpected error */
                    message: string;
                    /**
                     * @description HTTP ステータスコード
                     * @example 500
                     */
                    code: string;
                    /** @example [] */
                    errors?: string[];
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
